### ISSUE TITLE
Many collections with the same name

### ISSUE THREAD

**Issue by emenlu** [serpconnect/backend#3]
I tried to enter a number of entries starting by creating a new collection and then added entries to the queue. What I didn't notice was that I created a new collection for each element. 
- Should it be possible to have several collections with the same name?
- default should never be to create a new collection
- is there a way to merge several collections into one?

**Comment by smeets** [comment]
This probably happened because the submit page sends a collection name with each entry (instead of an id), which the backend detects and tries to be smart by creating a new collection with the provided name.
- I don't think we should enforce unique collection names, instead maybe promote the collection id as a means of identification?
- This is probably true, but we'll need to figure out a new way of how to submit entries to a new collection.
- No, there is not. It should, however, be somewhat easy to implement.

**Comment by smeets** [comment]
The fix:

Create a new collection a la profile page (with modal) and select it from the dropdown menu

**Comment by smeets** [comment]
This was fixed by emenlu/website#29 and 69fe87991e363b225b83dc6020f304240cabbfba
