### ISSUE TITLE
Add feature to import entries from a JSON/CSV file

### ISSUE THREAD

**Issue by emenlu** [serpconnect/backend#48]
- Add a button to upload using a file.

 - Specify JSON or CSV format.

 - Enqueue uploaded entries

**Comment by smeets** [comment]
Here's the current JSON format (from the [docs](http://serp-connect.readthedocs.io/en/update-api-spec/api/#submit-new-entry)):

```json
{
    "entryType": "challenge",
    "collection": 2,
    "description": "how to do software dev without cookies?",
    "date": "Mon Sep 28 1998 14:36:22 GMT-0700 (PDT)",
    "serpClassification": {
        "IMPROVING": ["cookies for software dev"],
        "INFORMATION": ["hungry hungry devs"]
    }
}
```

Ideally, we'd like the uploaded file to be an array of these things:
```json
[ entry, ..., entry ]
```

Because then it's just a matter of adding the entries to the queue.
    

If you want to add CSV then I think we need to either convert CSV into JSON (on frontend) or do some magic on the backend.

**Comment by smeets** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add feature to import entries from a JSON/CSV file](https://trello.com/c/UK9ziLWz/72-add-feature-to-import-entries-from-a-json-csv-file)
